spring.datasource.url=jdbc:mysql://127.0.0.1:3306/devconnect?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=root

spring.datasource.password=shajini
spring.jpa.hibernate.ddl-auto=update 
spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=50MB

spring.servlet.multipart.max-request-size=50MB
spring.jpa.show-sql=true

server.port=8080